# Generated by Django 4.2.11 on 2024-03-21 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersPermision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_for_activate', models.CharField(max_length=550)),
                ('token_is_used', models.BooleanField(default=False)),
                ('regulations', models.BooleanField(default=True)),
                ('marketing_conditions', models.BooleanField(default=True)),
                ('privacy_policy', models.BooleanField(default=True)),
                ('center_of_messagess', models.BooleanField(default=False)),
                ('sms_agreement', models.BooleanField(default=False)),
                ('email_agreement', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Lista Kontaktów',
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='user_images/')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Images',
            },
        ),
        migrations.CreateModel(
            name='UserRegeneratePassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_regenerate', models.CharField(max_length=35, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('create', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_regenerate', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Token',
            },
        ),
    ]
