# Generated by Django 4.2.11 on 2024-03-17 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_messages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatrequestforhelp',
            old_name='user',
            new_name='sender',
        ),
        migrations.AlterField(
            model_name='chatrequestforhelp',
            name='response_date',
            field=models.TextField(blank=True, null=True),
        ),
    ]
