# Generated by Django 4.2.11 on 2024-03-17 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_rename_user_chatrequestforhelp_sender_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatrequestforhelp',
            old_name='response_date',
            new_name='response',
        ),
    ]
